/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Signup = IDL.Record({
  'country' : IDL.Text,
  'ageRange' : IDL.Text,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'gender' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getAllSignupsSorted' : IDL.Func([], [IDL.Vec(Signup)], ['query']),
  'getAllSignupsSortedByEmail' : IDL.Func([], [IDL.Vec(Signup)], ['query']),
  'getSignupByEmail' : IDL.Func([IDL.Text], [IDL.Opt(Signup)], ['query']),
  'getSignupCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSignupCountForCountry' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getSignups' : IDL.Func([], [IDL.Vec(Signup)], ['query']),
  'isEmailRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'submitProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitSignup' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Signup = IDL.Record({
    'country' : IDL.Text,
    'ageRange' : IDL.Text,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'gender' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getAllSignupsSorted' : IDL.Func([], [IDL.Vec(Signup)], ['query']),
    'getAllSignupsSortedByEmail' : IDL.Func([], [IDL.Vec(Signup)], ['query']),
    'getSignupByEmail' : IDL.Func([IDL.Text], [IDL.Opt(Signup)], ['query']),
    'getSignupCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSignupCountForCountry' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getSignups' : IDL.Func([], [IDL.Vec(Signup)], ['query']),
    'isEmailRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'submitProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitSignup' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };